### ISSUE TITLE
[BUG] yankpad-local-category-to-major-mode: Symbol's function definition is void: when-let

### ISSUE THREAD

**Issue by zeltak** [Kungsgeten/yankpad#5]
Hi!

thx for the new upadtes really cool

the new yanpad i pulled from github seems to introduce a nasty bug that dosent allow me to use M-x

i get this error when i try to press M-x
```yankpad-local-category-to-major-mode: Symbol's function definition is void: when-let```

any clue?

best

Z

**Comment by Kungsgeten** [comment]
Which Emacs version do you have? I believe when-let was introduced in 24.4.

**Comment by Kungsgeten** [comment]
In order to use `when-let` I had to require `subr-x`. Should be fixed now, as long as you have Emacs 24.4 or later.

**Comment by zeltak** [comment]
Hi, i updated from get and even put (require 'subr-x)  in my config but i still get the same error
emacs details:

GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6)
 of 2015-09-10 on foutrelis

any clue? id be happy to help debug this

Z

**Comment by Kungsgeten** [comment]
I thought `when-let` was included in Emacs 24.4, but it turns out it wasn't introduced until Emacs 25. Anyway I have removed the dependency to `subr-x` so it should work in Emacs 24 now.

**Comment by zeltak** [comment]
yup i confirm its working now :)

thx

Z
